// ==================== 姿态字段 Schema ====================
export const POSE_FIELD_SCHEMA = [
  { key: 'pose_name', label: '姿态' },
  { key: 'framing', label: '景别' },
  { key: 'camera_angle', label: '角度' },
  { key: 'scene_theme', label: '场景主题' },
  { key: 'element_1', label: '元素1' },
  { key: 'element_2', label: '元素2' },
  { key: 'element_3', label: '元素3' },
  { key: 'special_lighting', label: '特殊光线' },
  { key: 'character_prop_1', label: '人物陪体-1' },
  { key: 'character_prop_2', label: '人物陪体-2' },
  { key: 'scene_prop_1', label: '场景陪体-1' },
  { key: 'scene_prop_2', label: '场景陪体-2' },
  { key: 'gender', label: '性别' },
  { key: 'age', label: '年龄' },
  { key: 'body_type_fit', label: '姿态适配身材' },
  { key: 'difficulty_level', label: '姿态难易程度' },
  { key: 'remarks', label: '备注' },
  { key: 'is_fixed_data', label: '是否固定数据' },
  { key: 'style_ins', label: 'ins风' },
  { key: 'style_seductive', label: '钓系姐感' },
  { key: 'style_relaxed', label: '松弛感' },
  { key: 'style_hk', label: '港片风' },
  { key: 'style_rich', label: '贵气千金' },
  { key: 'style_faceless', label: '不露脸氛围' },
  { key: 'style_tall_thin', label: '显高显瘦' },
  { key: 'style_vitality', label: '生命力/活人感' },
  { key: 'style_introvert', label: 'i人出片姿势' },
  { key: 'style_aesthetic_food', label: '漂亮饭' },
  { key: 'style_polaroid', label: '拍立得' },
  { key: 'style_ccd', label: 'CCD' },
  { key: 'style_anniversary', label: '纪念日打卡' },
  { key: 'style_birthday', label: '生日打卡' },
  { key: 'style_landmark', label: '地标' },
  { key: 'style_ancient', label: '古风' },
  { key: 'priority', label: '优先级' },
  { key: 'owner_1', label: '责任人1' },
  { key: 'owner_2', label: '责任人2' },
  { key: 'owner_3', label: '责任人3' },
] as const

// ==================== 引导词字段 Schema ====================
export const PROMPT_FIELD_SCHEMA = [
  { key: 'pose_code', label: '姿态编号' },
  { key: 'generated_prompt', label: '生成引导词' },
  { key: 'modified_prompt', label: '修改引导词' },
  { key: 'modifier', label: '修改人' },
  { key: 'word_count_check', label: '字数检查' },
  { key: 'check_owner', label: 'Check责任人' },
  { key: 'is_double_check', label: '是否双检' },
  { key: 'is_fixed_data', label: '是否固定数据' },
  { key: 'remarks', label: '备注' },
] as const

// ==================== 合并字段 Schema（用于 LabelingView） ====================
export const MERGED_FIELD_SCHEMA = [
  { key: 'pose_name', label: '姿态名称' },
  { key: 'framing', label: '景别' },
  { key: 'camera_angle', label: '角度' },
  { key: 'scene_theme', label: '场景主题' },
  { key: 'gender', label: '性别' },
  { key: 'age', label: '年龄' },
  { key: 'element_1', label: '元素1' },
  { key: 'element_2', label: '元素2' },
  { key: 'element_3', label: '元素3' },
  { key: 'special_lighting', label: '特殊光线' },
  { key: 'character_prop_1', label: '人物陪体1' },
  { key: 'character_prop_2', label: '人物陪体2' },
  { key: 'scene_prop_1', label: '场景陪体1' },
  { key: 'scene_prop_2', label: '场景陪体2' },
  { key: 'body_type_fit', label: '适配身材' },
  { key: 'difficulty_level', label: '难易程度' },
  { key: 'style_landmark', label: '地标' },
  { key: 'priority', label: '优先级' },
  { key: 'owner_1', label: '责1' },
  { key: 'owner_2', label: '责2' },
  { key: 'owner_3', label: '责3' },
  { key: 'style_ins', label: 'ins风' },
  { key: 'style_seductive', label: '钓系姐感' },
  { key: 'style_relaxed', label: '松弛感' },
  { key: 'style_hk', label: '港片风' },
  { key: 'style_rich', label: '贵气千金' },
  { key: 'style_faceless', label: '不露脸氛围' },
  { key: 'style_tall_thin', label: '显高显瘦' },
  { key: 'style_vitality', label: '生命力/活人感' },
  { key: 'style_introvert', label: 'i人出片姿势' },
  { key: 'style_aesthetic_food', label: '漂亮饭' },
  { key: 'style_polaroid', label: '拍立得' },
  { key: 'style_ccd', label: 'CCD' },
  { key: 'style_anniversary', label: '纪念日打卡' },
  { key: 'style_birthday', label: '生日打卡' },
  { key: 'style_ancient', label: '古风' },
  { key: 'pose_remarks', label: '姿态备注' },
  { key: 'generated_prompt', label: '生成引导词' },
  { key: 'modified_prompt', label: '修改引导词' },
  { key: 'modifier', label: '修改人' },
  { key: 'check_owner', label: 'Check责任人' },
  { key: 'remarks', label: '引导词备注' },
] as const

// ==================== 风格标签分组 ====================
export const STYLE_GROUP_1_KEYS = [
  'style_ins',
  'style_seductive',
  'style_relaxed',
  'style_hk',
  'style_rich',
  'style_faceless',
  'style_tall_thin',
  'style_vitality',
] as const

export const STYLE_GROUP_2_KEYS = [
  'style_introvert',
  'style_aesthetic_food',
  'style_polaroid',
  'style_ccd',
  'style_anniversary',
  'style_birthday',
  'style_ancient',
] as const

// ==================== 默认可见列配置 ====================
export const DEFAULT_POSE_VISIBLE_COLUMNS = [
  'pose_name',
  'framing',
  'camera_angle',
  'scene_theme',
  'element_1',
  'element_2',
  'element_3',
  'special_lighting',
  'character_prop_1',
  'character_prop_2',
  'scene_prop_1',
  'scene_prop_2',
  'gender',
  'age',
  'body_type_fit',
  'difficulty_level',
] as const

export const DEFAULT_PROMPT_VISIBLE_COLUMNS = [
  'modified_prompt',
  'modifier',
  'check_owner',
  'word_count_check',
  'is_double_check',
  'remarks',
] as const
